### ISSUE TITLE
Provide a way to customise the formatter

### ISSUE THREAD

**Issue by jarshwah** [click-contrib/click-log#1]
I wanted to add the datetime to the formatting string and couldn't find a good way to do so. Perhaps the `init` decorator could take a formatter or a function to call instead of basic_config? Anyhow, I've worked around this with monkey patching:

```
logger = logging.getLogger('myLogger')
handler = click_log.ClickHandler()
formatter = click_log.ColorFormatter('%(asctime)s - %(message)s')
handler.setFormatter(formatter)
click_log.core._default_handler = handler

@click_log.simple_verbosity_option()
@click_log.init(logger)
def cli(args):
    pass
```

Even this is suboptimal, as the level is forced to lowercase in the handler `emit()` method.

**Comment by untitaker** [comment]
I guess this needs to be done differently (perhaps initialize handler and formatter when `init` is called). PRs welcome!

**Comment by jarshwah** [comment]
I'm no longer personally interested in this. Feel free to reopen (or recreate) if still interested.
