### ISSUE TITLE
stderr

### ISSUE THREAD

**Issue by ericfrederich** [click-contrib/click-log#15]
I think the default behavior of logging is to output to stderr.  Perhaps this should do the same, or at least make it configurable.

For example, I have scripts which product JSON output which I like to pipe through `jq` command.  I can do this even with logging messages if I just use `logging.basicConfig()`, but with this project it goes to `stdout` and messes up my JSON

**Comment by untitaker** [comment]
Everything worse than info goes to stderr. Is this what you are looking for?

**Comment by alanjds** [comment]
Yes. I would like to put even INFO to stderr, as an option

**Comment by untitaker** [comment]
I released 0.3.0 to address this. In hindsight using stdout does not make sense

**Comment by Toilal** [comment]
> as an option

@untitaker I think this was important. Logging to stderr is not expected at all, this is not the default of logging module, and any other logging module that I know in any other language. It should at least be configurable, but why making this the default without any possibility to override ?

Are you still maintaining this module ?
