### ISSUE TITLE
Add a `no-color` option, method or parameter to disable colouring globally

### ISSUE THREAD

**Issue by kdeldycke** [click-contrib/click-log#30]
I use `click-log` in my CLIs to provides color-coded messages depending on levels and it works great! But I also need to provide to my users a `--no-color` option at the CLI level to strip all ANSI codes.

The way I actually do it consist in hacking my way to the `ColorFormatter.colors` variable and reset all its color configuration. Here is my implementation: https://github.com/kdeldycke/meta-package-manager/commit/d960f29c82c93bdef0c584c0fbee88e2c5ef7f95

To make things future-proof and avoid hacking into `click-log` implementation details, I'd like to have a sort of global parameter or a method to disable coloring entirely.

**Comment by untitaker** [comment]
The click context contains a color attribute you can set to globally disable color output. There's no need to patch anything at all: https://click.palletsprojects.com/en/8.0.x/api/?highlight=context#context

**Comment by kdeldycke** [comment]
Thanks @untitaker for the feedback. After I filled that bug I spent time digging around Click code and stumbled upon the `color` parameter on `Context`. It does fix my issue.

I ended up implemented a generic `--no-color` option for others to reuse in my [`click-extra`](https://github.com/kdeldycke/click-extra) package.

We can consider this as closed.
