### ISSUE TITLE
The short option `-v` as `--verbosity` is not documented.

### ISSUE THREAD

**Issue by AtsushiSakai** [click-contrib/click-log#32]
Hi. First of all, thank you for providing great OSS.

I think the short option `-v` as `--verbosity` is useful, but it is not documented. I think it should be.
 
If maintainers agree with it, I can create a PR for it.

**Comment by untitaker** [comment]
Sure!

**Comment by AtsushiSakai** [comment]
@untitaker Thanks!! I created #33. PTAL.
